version: '3.8'

services:
  diablodex-api:
    build: 
      context: . 
    container_name: diablodex-api
    ports:
      - "8081:8081"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - SOAP_CLIENT_URL=http://diablo-api:8055/ws
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:4444
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_OAUTH2=TRACE
    depends_on:
      - diablo-api
      - redis
      - hydra
    networks:
      - diablo-net

  diablo-api:
    build:
      context: ../DiabloApi 
    container_name: diablo-api
    ports:
      - "8055:8055" 
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://diablo-mysql:3306/diablo_db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SERVER_PORT=8055
    depends_on:
      diablo-mysql:
        condition: service_healthy 
    networks:
      - diablo-net

  diablo-mysql:
    image: mysql:8.0
    container_name: diablo-mysql
    environment:
      - MYSQL_DATABASE=diablo_db
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - "3366:3306"
    volumes:
      - mysql_data_diablo:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
    networks:
      - diablo-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - diablo-net

  db-hydra:
    image: postgres:15
    container_name: db-hydra
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_hydra:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hydra"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - diablo-net

  hydra:
    image: oryd/hydra:v2.2
    container_name: hydra
    depends_on:
      db-hydra:
        condition: service_healthy
    environment:
      - DSN=postgres://hydra:secret@db-hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_SELF_PUBLIC=http://localhost:4444
      - SECRETS_SYSTEM=thisisaverysecretkey123
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      - LOG_LEVEL=debug
      - STRATEGIES_ACCESS_TOKEN=jwt
    entrypoint: ["/bin/sh", "-c"]
    command: ["hydra migrate sql -e --yes && hydra serve all --dev"]
    ports:
      - "4444:4444"
      - "4445:4445"
    networks:
      - diablo-net
    restart: unless-stopped

volumes:
  mysql_data_diablo:
  postgres_data_hydra:

networks:
  diablo-net:
    driver: bridge